name: Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies for frontend
        run: |
          cd frontend/react
          npm install

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Install dependencies for backend
        run: |
          cd backend/java-spring-boot
          mvn install -DskipTests
      - run: chmod +x backend/java-spring-boot/mvnw

      - uses: snyk/actions/setup@master
      - name: Snyk test
        run: snyk test --all-projects --detection-depth=3
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}