name: Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies for frontend
        run: |
          cd frontend/react
          npm install
      - name: Run Snyk to check for vulnerabilities on react frontend
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=frontend/react/package.json

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Install dependencies for backend
        run: |
          cd backend/java-spring-boot
          mvn install -DskipTests

      - name: Run Snyk to check for vulnerabilities on java-spring-boot backend
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=backend/java-spring-boot/pom.xml -d